/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 Three.glb
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Three.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <PerspectiveCamera name="asddafspy" makeDefault={false} far={1000} near={0.1} fov={21.27} position={[-12.03, 6.71, 0.7]} rotation={[-1.54, -1.15, -1.54]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.002']} position={[1.64, 0.12, 0.7]} rotation={[0, 0, -1.6]} scale={[0.56, 1.96, 2.11]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.003']} position={[1.82, 0.78, 0.56]} rotation={[-Math.PI, 0, 0]} scale={[-1.45, -0.03, -1.45]} />
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Material.003']} position={[1.4, 0.69, 2.5]} rotation={[0, 0, -Math.PI]} scale={0.09} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Material.012']} position={[0.4, 0.51, 2.54]} rotation={[0, 0, -Math.PI / 2]} scale={0.33} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.004']} position={[2.32, 2.17, 0.05]} rotation={[0, 0, -1.86]} scale={[0.54, 0.2, 0.54]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.004']} position={[1.53, 1.33, -1.84]} rotation={[-0.43, 0.39, -1.79]} scale={[0.32, 0.08, 0.88]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.006']} position={[2.08, 0.87, -1.81]} rotation={[0, 0, -Math.PI / 2]} scale={[0.56, 0.04, 0.4]} />
        <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Material.004']} position={[3.28, 0.93, 3.02]} scale={0.24} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.004']} position={[3.48, 0.93, 2.9]} scale={[1.3, 0.08, 0.08]} />
        <mesh name="Cylinder008" geometry={nodes.Cylinder008.geometry} material={materials['Material.002']} position={[1.82, 0.7, 0.56]} rotation={[-Math.PI, 0, 0]} scale={[-1.6, -0.06, -1.6]} />
        <mesh name="Sphere003" geometry={nodes.Sphere003.geometry} material={materials['Material.007']} position={[0.41, 0.48, 2.54]} scale={0.34} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['Material.002']} position={[1.8, 0.8, 0.58]} scale={[0.15, 0.36, 0.15]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.005']} position={[1.02, 0.87, -1.81]} rotation={[0, 0, -Math.PI / 2]} scale={[0.56, 0.04, 0.4]} />
        <mesh name="Cylinder010" geometry={nodes.Cylinder010.geometry} material={materials['Material.007']} position={[1.6, 1.26, -1.81]} rotation={[0, 0, -Math.PI / 2]} scale={[0.07, 0.67, 0.07]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.004']} position={[1.6, 0.72, -1.82]} rotation={[0, 0, -0.03]} scale={[1.49, 0.09, 0.37]} />
        <mesh name="Cone" geometry={nodes.Cone.geometry} material={materials['Material.007']} position={[2.23, 1.56, 0.18]} rotation={[-3.05, -0.48, 0.44]} scale={[0.11, 0.13, 0.1]} />
        <group name="Cube008" position={[1.64, -0.09, 0.7]} rotation={[0, 0, -1.6]} scale={[0.58, 2.03, 2.16]}>
          <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials['Material.001']} />
          <mesh name="Cube015_1" geometry={nodes.Cube015_1.geometry} material={nodes.Cube015_1.material} />
        </group>
        <mesh name="Cylinder011" geometry={nodes.Cylinder011.geometry} material={materials['Material.003']} position={[1.82, 0.83, 0.56]} rotation={[-Math.PI, 0, 0]} scale={[-1.45, -0.01, -1.45]} />
        <mesh name="Cylinder012" geometry={nodes.Cylinder012.geometry} material={materials['Material.013']} position={[1.82, 0.93, 0.56]} rotation={[-Math.PI, 0, 0]} scale={[-1.45, -0.01, -1.45]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Three.glb')
